AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - gemfiles/**/*
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  Enabled: true
Layout/LineLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/EmptyWhen:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/RedundantCopDisableDirective:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/SuppressedException:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/GuardClause:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RaiseArgs:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: false
